### ISSUE TITLE
Optimize atree to reduce Flow's mtrie size and reduce number of reads

### ISSUE THREAD

**Issue by fxamacker** [onflow/atree#292]
### Issue To Be Solved

We should make Execution Nodes use less memory without sacrificing performance.  Also, given the same user data growth rate, we should reduce the rate of Execution Node system requirements growth.

### Suggested Solution and Implementation

- https://github.com/onflow/atree/pull/342
- Also see https://github.com/dapperlabs/flow-go/issues/6320 and other PRs

Solution requires changes to onflow/atree, onflow/cadence, onflow/flow-go, and data migration.

See also:
- https://github.com/dapperlabs/flow-go/issues/6320
- https://github.com/onflow/flow-go/issues/1744
- https://github.com/onflow/cadence/issues/1854

### Testnet Results with Atree Inlining & Deduplication

![image](https://github.com/user-attachments/assets/e72ea2eb-7d40-48cb-b077-d4f4c9a35eca)

Atree inlining and data deduplication on testnet indicates:
- Reduced memory usage by about 1/2 (hundreds of GB RAM) on each Execution Node
- Block execution speed was also 7% faster according to test results shared by @j1010001
- Significantly reduced number of payloads
- Significantly reduced number of nodes (non-payloads)
- Significantly reduced total combined size of all payloads
- Reduced data growth rate (given same data)
- Also expected to benefit other db and software (even if not on EN) if they store/index/cache payloads

NOTE:  Impact on testnet and mainnet will differ, depending on actual usage, data, etc.

#### Impact on memory and storage size

![image](https://github.com/onflow/atree/assets/33205765/8dc26fe9-ab93-4589-a361-787d7b9025e7)

![image](https://github.com/onflow/atree/assets/33205765/b30fa1a4-8f37-4718-8298-02fdddb817c1)

These charts should probably be updated when time allows.

#### Impact on payload count and node count

![image](https://github.com/onflow/atree/assets/33205765/46f6b0ad-b87c-4121-b50c-4bc76e8fb3d1)

![image](https://github.com/onflow/atree/assets/33205765/3b04dde1-1a82-4b82-81d8-110f80e83042)

These charts should probably be updated when time allows.

**Comment by j1010001** [comment]
Complete TPS throughput test before closing:

Test 1 - non-inlined state
- [ ] Spin up an EN 
- [ ] remove exec results for ~100K blocks 
- [ ] re-execute blocks on a non-inline state - capture TPS + block exec time

Test 2 - atree-inlined state
- [ ] migrate the state with Atree inlining
- [ ] remove exec results for ~100K blocks 
- [ ] re-execute blocks on a atree-inlined state - capture TPS + block exec time

**Comment by fxamacker** [comment]
@j1010001 thanks again for providing testnet memory reduction screenshot we can share on GitHub!

- atree smoke tests completed 517 hours with no problems (I manuallly stopped it last week)
- I also manually compared `diff-states` results (1.8GB JSONL report) after reexecuting 1,000 blocks
  - https://discord.com/channels/613813861610684416/1108968095982293002/1266058761412280341 
- these are in addition to `check-storage` command showing no problems on testnet data after spork

Closing this as completed.  Please re-open if needed! :pray:
